version: "3"

services:
  # kafka module
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2182"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # this gets the docker host ip... more or less
      HOSTNAME_COMMAND: "ip route | grep default | awk '{print $$3}'"
      KAFKA_ADVERTISED_LISTENERS: DOCKER://kafka:9094,HOST://localhost:9092
      KAFKA_LISTENERS: DOCKER://:9094,HOST://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CREATE_TOPICS: "posts:1:1,comments:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # reddit scraper
  reddit-client:
    build: "./reddit-client"
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9094
    restart: on-failure   # allow restart by itself
  # statistics database
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: reddit_stats
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_USER_PASSWORD: admin
  # visualization tool
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./init-data/grafana-provisioning:/etc/grafana/provisioning
